name: nearby_hungry_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (all compatible versions)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  geolocator: ^10.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.6
  firebase_messaging: ^16.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  dropdown_button2: ^1.9.4



  # Google Sign-In
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/app_logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center


